import type { Metadata } from "next";
import "./globals.scss";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ThemeToggleProvider } from "@/components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeToggleProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeToggleProvider>
      </body>
    </html>
  );
}
