import type { Metadata } from "next";

import "./globals.scss";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ThemeToggleProvider } from "@/components/ThemeToggle";
import { QueryProvider } from "@/components/QueryProvider";
import { ProfileProvider } from "@/components/ProfileProvider";
import { ProThemesProvider } from "@/components/ProThemesProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ProfileProvider>
            <ProThemesProvider>
              <ThemeToggleProvider>
                <Navbar />
                {children}
                <Footer />
              </ThemeToggleProvider>
            </ProThemesProvider>
          </ProfileProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
